# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='altemadb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='bunkaidb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='flaudb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='lineid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500, verbose_name='userid')),
            ],
        ),
        migrations.CreateModel(
            name='maltinedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='planetdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='progressivedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='sensedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
        migrations.CreateModel(
            name='warpdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='アーティスト名')),
            ],
        ),
    ]
