# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_trekkiedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaudb',
            name='test',
            field=models.CharField(default='hh', max_length=500, verbose_name='タイプ'),
        ),
    ]
