# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_remove_flaudb_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='diggerdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500, verbose_name='userid')),
            ],
        ),
    ]
