# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0021_auto_20170317_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='no', max_length=500, verbose_name='Label')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
