# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0022_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='date',
        ),
    ]
