# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0026_auto_20170428_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='altemadb',
        ),
        migrations.DeleteModel(
            name='brainfeederdb',
        ),
        migrations.DeleteModel(
            name='bunkaidb',
        ),
        migrations.DeleteModel(
            name='diggerdb',
        ),
        migrations.DeleteModel(
            name='edbangerdb',
        ),
        migrations.DeleteModel(
            name='flaudb',
        ),
        migrations.DeleteModel(
            name='luckymedb',
        ),
        migrations.DeleteModel(
            name='maddb',
        ),
        migrations.DeleteModel(
            name='neverdb',
        ),
        migrations.DeleteModel(
            name='owsladb',
        ),
        migrations.DeleteModel(
            name='planetdb',
        ),
        migrations.DeleteModel(
            name='progressivedb',
        ),
        migrations.DeleteModel(
            name='revealeddb',
        ),
        migrations.DeleteModel(
            name='rsdb',
        ),
        migrations.DeleteModel(
            name='sensedb',
        ),
        migrations.DeleteModel(
            name='spinnindb',
        ),
        migrations.DeleteModel(
            name='trekkiedb',
        ),
        migrations.DeleteModel(
            name='warpdb',
        ),
        migrations.DeleteModel(
            name='wediditdb',
        ),
    ]
