# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0035_auto_20170514_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='labelset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='--', max_length=100, verbose_name='Label')),
            ],
        ),
        migrations.AddField(
            model_name='lineid',
            name='rec',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=500, verbose_name='record'),
        ),
        migrations.AddField(
            model_name='lineid',
            name='state',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=500, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='lineid',
            name='label',
            field=models.ManyToManyField(to='label.labelset'),
        ),
    ]
