# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0036_auto_20170529_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineid',
            old_name='state',
            new_name='kaijo',
        ),
        migrations.AddField(
            model_name='lineid',
            name='toroku',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=500, verbose_name='state'),
        ),
    ]
